version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.19
      
    steps:
      - checkout

      - run: make dist
      - store_artifacts:
          path: ./dist/
          destination: artifacts
